services:
  warp2:
    image: caomingjun/warp:latest
    environment:
      WARP_SLEEP: "2"
    cap_add:
      - NET_ADMIN
    volumes:
      - warp2_state:/var/lib/cloudflare-warp
    restart: unless-stopped

  warp3:
    image: caomingjun/warp:latest
    environment:
      WARP_SLEEP: "2"
    cap_add:
      - NET_ADMIN
    volumes:
      - warp3_state:/var/lib/cloudflare-warp
    restart: unless-stopped

volumes:
  warp2_state:
  warp3_state:
