import { ImagePlus, Play, Sparkles, Square, Trash2 } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { usePublicAuth } from "@/public/auth/public-auth";
import { ImageGrid } from "@/public/components/image-grid";
import { VideoGrid } from "@/public/components/video-grid";
import { editImage, generatedImage, imageFromEdit, startImage, stopImages, streamImage, type GeneratedImage } from "@/public/features/image/image-api";
import { startVideo, stopVideos, streamVideo, videoPostID, type VideoItem } from "@/public/features/video/video-api";
import { filesToAssets } from "@/public/lib/media";

export function NsfwPage() {
  const { key } = usePublicAuth(); const [imagePrompt, setImagePrompt] = useState(""); const [videoPrompt, setVideoPrompt] = useState(""); const [ratio, setRatio] = useState("16:9"); const [parallel, setParallel] = useState("4"); const [resolution, setResolution] = useState("480p"); const [length, setLength] = useState("6"); const [images, setImages] = useState<GeneratedImage[]>([]); const [selected, setSelected] = useState<GeneratedImage | null>(null); const [videos, setVideos] = useState<VideoItem[]>([]); const [activeVideo, setActiveVideo] = useState<VideoItem | null>(null); const [localImage, setLocalImage] = useState(""); const [imageRunning, setImageRunning] = useState(false); const [videoRunning, setVideoRunning] = useState(false); const [editPrompt, setEditPrompt] = useState(""); const imageTasks = useRef<string[]>([]); const videoTasks = useRef<string[]>([]); const imageControllers = useRef<AbortController[]>([]); const videoControllers = useRef(new Map<string, AbortController>());
  async function stopCandidates() { imageControllers.current.forEach((item) => item.abort()); await stopImages(key, imageTasks.current).catch(() => undefined); imageControllers.current = []; imageTasks.current = []; setImageRunning(false); }
  async function generateCandidates() { if (!imagePrompt.trim() || imageRunning) return; setImages([]); setSelected(null); setImageRunning(true); let collected = 0; try { const starts = await Promise.all(Array.from({ length: 3 }, () => startImage(key, { prompt: imagePrompt.trim(), aspect_ratio: ratio, nsfw: true, pro: false }))); imageTasks.current = starts.map((item) => item.task_id); imageControllers.current = starts.map(() => new AbortController()); starts.forEach((item, index) => void streamImage(key, item.task_id, (event) => { const image = generatedImage(event, imagePrompt); if (!image || collected >= 6) return; collected += 1; setImages((items) => [...items, image]); if (collected >= 6) void stopCandidates(); }, imageControllers.current[index].signal).catch((error) => { if (!imageControllers.current[index].signal.aborted) toast.error(error.message); })); } catch (error) { setImageRunning(false); toast.error(error instanceof Error ? error.message : "候选图创建失败"); } }
  async function editSelected() { if (!selected || !editPrompt.trim()) return; try { const payload = await editImage(key, { prompt: editPrompt.trim(), parent_post_id: selected.parentPostID, source_image_url: selected.sourceURL }); const image = imageFromEdit(payload, editPrompt.trim()); if (image) { setImages((items) => [image, ...items]); setSelected(image); setEditPrompt(""); toast.success("候选图编辑完成"); } } catch (error) { toast.error(error instanceof Error ? error.message : "编辑失败"); } }
  function watchVideo(taskID: string, label: string) { const controller = new AbortController(); videoControllers.current.set(taskID, controller); setVideos((items) => [{ id: taskID, taskID, url: "", prompt: videoPrompt, progress: 0, status: "running", postID: "", displayName: label, createdAt: Date.now() }, ...items]); void streamVideo(key, taskID, (update) => setVideos((items) => items.map((item) => item.taskID !== taskID ? item : { ...item, progress: update.progress ?? item.progress, url: update.url || item.url, postID: videoPostID(update.url || item.url), status: update.error ? "failed" : update.url || update.done ? "completed" : "running", error: update.error })), controller.signal).finally(() => { videoControllers.current.delete(taskID); if (!videoControllers.current.size) setVideoRunning(false); }); }
  async function generateVideos(extension?: VideoItem) { const source = localImage || selected?.sourceURL || selected?.url; if (!source && !extension) return toast.error("请先选择候选图或上传本地参考图"); if (extension && !extension.postID) return toast.error("当前视频缺少 postId"); setVideoRunning(true); try { const result = await startVideo(key, { prompt: videoPrompt.trim(), aspect_ratio: ratio, video_length: extension ? 10 : Number(length), resolution_name: resolution, preset: videoPrompt.trim() ? "custom" : "spicy", concurrent: extension ? 1 : Number(parallel), image_url: extension ? undefined : source, source_image_url: extension ? undefined : source, is_video_extension: Boolean(extension), extend_post_id: extension?.postID, original_post_id: extension?.originalPostID || extension?.postID, file_attachment_id: extension?.originalPostID || extension?.postID, video_extension_start_time: 0, stitch_with_extend: Boolean(extension) }); const ids = result.task_ids?.length ? result.task_ids : [result.task_id]; videoTasks.current = ids; ids.forEach((id, index) => watchVideo(id, extension ? "延长视频" : `NSFW 视频 ${index + 1}`)); } catch (error) { setVideoRunning(false); toast.error(error instanceof Error ? error.message : "视频任务创建失败"); } }
  async function stopVideoRun() { videoControllers.current.forEach((item) => item.abort()); videoControllers.current.clear(); await stopVideos(key, videoTasks.current).catch(() => undefined); setVideoRunning(false); }
  return <section><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold">NSFW 工作台</h1><p className="mt-1 text-sm text-muted-foreground">候选图、图生视频与延长集中处理</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => { setImages([]); setSelected(null); }}><Trash2 className="size-4" />清空图片</Button><Button variant="outline" onClick={() => { setVideos([]); setActiveVideo(null); }}><Trash2 className="size-4" />清空视频</Button></div></div>
    <div className="mb-5 grid gap-4 border-y py-4 lg:grid-cols-2"><div><label className="mb-2 block text-sm font-medium">候选图提示词</label><Textarea value={imagePrompt} onChange={(event) => setImagePrompt(event.target.value)} className="min-h-28" placeholder="描述要生成的 NSFW 候选图" /><div className="mt-3 flex gap-2">{imageRunning ? <Button variant="destructive" onClick={() => void stopCandidates()}><Square className="size-4" />停止候选</Button> : <Button onClick={() => void generateCandidates()} disabled={!imagePrompt.trim()}><Sparkles className="size-4" />生成 6 张</Button>}<Select value={ratio} onValueChange={setRatio}><SelectTrigger className="w-28"><SelectValue /></SelectTrigger><SelectContent>{["16:9","9:16","3:2","2:3","1:1"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div></div><div><label className="mb-2 block text-sm font-medium">视频提示词</label><Textarea value={videoPrompt} onChange={(event) => setVideoPrompt(event.target.value)} className="min-h-28" placeholder="留空使用 spicy，填写则使用 custom" /><div className="mt-3 grid grid-cols-3 gap-2"><Select value={parallel} onValueChange={setParallel}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["1","2","3","4"].map((value) => <SelectItem key={value} value={value}>{value} 路</SelectItem>)}</SelectContent></Select><Select value={resolution} onValueChange={setResolution}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["480p","720p"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Select value={length} onValueChange={setLength}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["6","10","15"].map((value) => <SelectItem key={value} value={value}>{value} 秒</SelectItem>)}</SelectContent></Select></div></div></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]"><div className="space-y-6"><div><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">候选图片</h2><span className="text-xs text-muted-foreground">{selected ? "已选择 1 张" : `${images.length} 张`}</span></div><ImageGrid images={images} selected={new Set(selected ? [selected.id] : [])} onSelect={(id) => setSelected(images.find((item) => item.id === id) || null)} onOpen={setSelected} onEdit={setSelected} /></div><div><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">视频结果</h2><span className="text-xs text-muted-foreground">{videos.length} 个</span></div><VideoGrid videos={videos} activeID={activeVideo?.id} onActivate={setActiveVideo} /></div></div>
      <aside className="space-y-4"><div className="border p-4"><h2 className="mb-3 text-sm font-semibold">选中图片与视频操作</h2>{selected ? <img src={selected.url} alt={selected.prompt} className="aspect-square w-full object-cover" /> : <div className="grid aspect-square place-items-center bg-muted text-sm text-muted-foreground">选择一张候选图</div>}<Textarea value={editPrompt} onChange={(event) => setEditPrompt(event.target.value)} className="mt-3 min-h-24" placeholder="输入图片编辑要求" /><Button variant="outline" className="mt-2 w-full" onClick={() => void editSelected()} disabled={!selected || !editPrompt.trim()}><Sparkles className="size-4" />编辑选中图</Button><label className="mt-3 flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-md border text-sm"><ImagePlus className="size-4" />上传本地参考图<input type="file" accept="image/*" className="hidden" onChange={(event) => void filesToAssets(event.target.files || [], 1).then((items) => setLocalImage(items[0]?.data || ""))} /></label>{localImage && <Input className="mt-2" value="已加载本地参考图" readOnly />}{videoRunning ? <Button variant="destructive" className="mt-3 w-full" onClick={() => void stopVideoRun()}><Square className="size-4" />中断视频</Button> : <Button className="mt-3 w-full" onClick={() => void generateVideos()} disabled={!selected && !localImage}><Play className="size-4" />选中图生视频</Button>}{activeVideo?.url && <Button variant="outline" className="mt-2 w-full" onClick={() => void generateVideos(activeVideo)} disabled={!activeVideo.postID || videoRunning}>延长当前视频</Button>}</div>{activeVideo?.url && <video src={activeVideo.url} controls playsInline className="aspect-video w-full bg-black" />}</aside></div>
  </section>;
}
