import { ImagePlus, Library, Play, Plus, RotateCcw, Scissors, Square, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { usePublicAuth } from "@/public/auth/public-auth";
import { VideoGrid } from "@/public/components/video-grid";
import { resolveParentPost } from "@/public/features/image/image-api";
import { cachedVideo, listCachedVideos, renameVideo, startVideo, stopVideos, streamVideo, videoPostID, type VideoItem } from "@/public/features/video/video-api";
import { extractParentPostID, filesToAssets, imageSource, type UploadAsset } from "@/public/lib/media";

export function VideoPage() {
  const { key } = usePublicAuth(); const [prompt, setPrompt] = useState(""); const [references, setReferences] = useState<UploadAsset[]>([]); const [parentInput, setParentInput] = useState(""); const [ratio, setRatio] = useState("3:2"); const [length, setLength] = useState("6"); const [resolution, setResolution] = useState("480p"); const [preset, setPreset] = useState("normal"); const [concurrent, setConcurrent] = useState("1"); const [videos, setVideos] = useState<VideoItem[]>([]); const [active, setActive] = useState<VideoItem | null>(null); const [running, setRunning] = useState(false); const [cacheOpen, setCacheOpen] = useState(false); const [renameTarget, setRenameTarget] = useState<VideoItem | null>(null); const [renameValue, setRenameValue] = useState(""); const [extendPrompt, setExtendPrompt] = useState(""); const [extendTime, setExtendTime] = useState(0); const [duration, setDuration] = useState(0); const controllers = useRef(new Map<string, AbortController>()); const taskIDs = useRef<string[]>([]);
  useEffect(() => { const paste = (event: ClipboardEvent) => { const files = Array.from(event.clipboardData?.files || []).filter((file) => file.type.startsWith("image/")); if (files.length) void filesToAssets(files, Math.max(0, 8 - references.length)).then((items) => setReferences((value) => [...value, ...items].slice(0, 8))); }; window.addEventListener("paste", paste); return () => window.removeEventListener("paste", paste); }, [references.length]);
  async function addParent() { const id = extractParentPostID(parentInput); if (!id) return toast.error("未识别到 parentPostId"); try { const payload = await resolveParentPost(key, id); const url = imageSource(payload); if (!url) throw new Error("未找到图片地址"); setReferences((items) => [...items, { id, name: id, mime: "image/jpeg", data: url }].slice(0, 8)); setParentInput(""); } catch (error) { toast.error(error instanceof Error ? error.message : "加载失败"); } }
  function watch(taskID: string, label: string) { const controller = new AbortController(); controllers.current.set(taskID, controller); setVideos((items) => [{ id: taskID, taskID, url: "", prompt, progress: 0, status: "running", postID: "", displayName: label, createdAt: Date.now() }, ...items]); void streamVideo(key, taskID, (update) => setVideos((items) => items.map((item) => item.taskID !== taskID ? item : { ...item, progress: update.progress ?? item.progress, url: update.url || item.url, postID: videoPostID(update.url || item.url), status: update.error ? "failed" : update.url || update.done ? "completed" : "running", error: update.error })), controller.signal).catch((error) => { if (!controller.signal.aborted) toast.error(error.message); }).finally(() => { controllers.current.delete(taskID); if (!controllers.current.size) setRunning(false); }); }
  async function generate(bodyOverride?: Record<string, unknown>) { if (running) return; if (!prompt.trim() && !references.length && !bodyOverride) return toast.error("请输入提示词或添加参考图"); setRunning(true); try { const result = await startVideo(key, { prompt: prompt.trim(), aspect_ratio: ratio, video_length: Number(length), resolution_name: resolution, preset, concurrent: Number(concurrent), image_references: references.map((item) => item.data), source_image_urls: references.map((item) => item.data), ...(bodyOverride || {}) }); const ids = result.task_ids?.length ? result.task_ids : [result.task_id]; taskIDs.current = ids; ids.forEach((id, index) => watch(id, bodyOverride ? "延长视频" : `视频 ${videos.length + index + 1}`)); } catch (error) { setRunning(false); toast.error(error instanceof Error ? error.message : "创建视频失败"); } }
  async function stop() { controllers.current.forEach((value) => value.abort()); controllers.current.clear(); await stopVideos(key, taskIDs.current).catch(() => undefined); taskIDs.current = []; setRunning(false); }
  async function openCache() { setCacheOpen(true); try { const payload = await listCachedVideos(key); const values = (payload.items || []).map(cachedVideo); setVideos((items) => { const seen = new Set(items.map((item) => item.url || item.id)); return [...items, ...values.filter((item) => !seen.has(item.url || item.id))]; }); } catch (error) { toast.error(error instanceof Error ? error.message : "读取缓存失败"); } }
  async function saveRename() { if (!renameTarget || !renameValue.trim()) return; try { await renameVideo(key, renameTarget, renameValue.trim()); setVideos((items) => items.map((item) => item.id === renameTarget.id ? { ...item, displayName: renameValue.trim() } : item)); setRenameTarget(null); toast.success("名称已更新"); } catch (error) { toast.error(error instanceof Error ? error.message : "重命名失败"); } }
  async function extend() { if (!active?.postID) return toast.error("当前视频没有可用 postId，请从缓存中选择"); await generate({ prompt: extendPrompt.trim(), concurrent: 1, video_length: Number(length), is_video_extension: true, extend_post_id: active.postID, video_extension_start_time: extendTime, original_post_id: active.originalPostID || active.postID, file_attachment_id: active.originalPostID || active.postID, stitch_with_extend: true }); }
  return <section><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">Video 视频工作台</h1><p className="mt-1 text-sm text-muted-foreground">{running ? "任务运行中" : `${videos.length} 个视频`}</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void openCache()}><Library className="size-4" />缓存视频</Button><Button variant="outline" onClick={() => { setVideos([]); setActive(null); }}><RotateCcw className="size-4" />清空</Button>{running ? <Button variant="destructive" onClick={() => void stop()}><Square className="size-4" />停止</Button> : <Button onClick={() => void generate()}><Play className="size-4" />生成</Button>}</div></div>
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_420px]"><div className="space-y-5"><div className="border p-4"><div className="mb-3 flex flex-wrap gap-2"><label className="inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-md border px-3 text-sm"><ImagePlus className="size-4" />添加参考图<input type="file" accept="image/*" multiple className="hidden" onChange={(event) => void filesToAssets(event.target.files || [], Math.max(0, 8 - references.length)).then((items) => setReferences((value) => [...value, ...items].slice(0, 8)))} /></label><div className="flex min-w-64 flex-1 gap-2"><Input value={parentInput} onChange={(event) => setParentInput(event.target.value)} placeholder="parentPostId" /><Button variant="outline" size="icon" onClick={() => void addParent()} aria-label="添加 parentPostId"><Plus className="size-4" /></Button></div></div>{references.length ? <div className="grid grid-cols-4 gap-2 sm:grid-cols-6">{references.map((item) => <div key={item.id} className="relative aspect-square overflow-hidden border"><img src={item.data} alt={item.name} className="size-full object-cover" /><button className="absolute right-0 top-0 grid size-8 place-items-center bg-background/90" onClick={() => setReferences((values) => values.filter((value) => value.id !== item.id))} aria-label={`移除 ${item.name}`}><X className="size-4" /></button></div>)}</div> : <p className="text-sm text-muted-foreground">支持最多 8 张图片、拖放与粘贴</p>}</div>
      <div className="border p-4"><label className="mb-2 block text-sm font-medium">视频提示词</label><Textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} className="min-h-28" placeholder="描述镜头、动作和风格" /><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3"><Select value={ratio} onValueChange={setRatio}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["3:2","2:3","16:9","9:16","1:1"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Select value={length} onValueChange={setLength}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["6","10","15"].map((value) => <SelectItem key={value} value={value}>{value} 秒</SelectItem>)}</SelectContent></Select><Select value={resolution} onValueChange={setResolution}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["480p","720p"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Select value={preset} onValueChange={setPreset}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["normal","fun","spicy","custom"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Select value={concurrent} onValueChange={setConcurrent}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["1","2","3","4"].map((value) => <SelectItem key={value} value={value}>{value} 路</SelectItem>)}</SelectContent></Select></div></div>
      <div><h2 className="mb-3 text-sm font-semibold">视频历史</h2><VideoGrid videos={videos} activeID={active?.id} onActivate={(item) => { setActive(item); setExtendTime(0); }} onRename={(item) => { setRenameTarget(item); setRenameValue(item.displayName); }} /></div></div>
      <aside className="border p-4"><h2 className="mb-3 text-sm font-semibold">当前视频与延长</h2>{active?.url ? <><video src={active.url} controls playsInline className="aspect-video w-full bg-black" onLoadedMetadata={(event) => { setDuration(event.currentTarget.duration || 0); setExtendTime(Math.min(extendTime, event.currentTarget.duration || 0)); }} /><div className="mt-3"><label className="text-xs">延长起点 {extendTime.toFixed(3)}s</label><input type="range" min="0" max={Math.max(duration, 0.001)} step="0.001" value={extendTime} onChange={(event) => setExtendTime(Number(event.target.value))} className="mt-2 w-full" /></div><Textarea value={extendPrompt} onChange={(event) => setExtendPrompt(event.target.value)} className="mt-3 min-h-24" placeholder="留空使用 spicy，或描述接下来的画面" /><Button className="mt-3 w-full" onClick={() => void extend()} disabled={running || !active.postID}><Scissors className="size-4" />从当前时间延长</Button>{!active.postID && <p className="mt-2 text-xs text-muted-foreground">从缓存选择带 postId 的视频后可延长</p>}</> : <div className="grid min-h-64 place-items-center text-center text-sm text-muted-foreground">选择一个已完成视频进入工作区</div>}</aside></div>
    <Dialog open={Boolean(renameTarget)} onOpenChange={(open) => !open && setRenameTarget(null)}><DialogContent><DialogHeader><DialogTitle>重命名视频</DialogTitle></DialogHeader><Input value={renameValue} onChange={(event) => setRenameValue(event.target.value)} /><Button onClick={() => void saveRename()}>保存</Button></DialogContent></Dialog>
    <Dialog open={cacheOpen} onOpenChange={setCacheOpen}><DialogContent className="max-w-5xl"><DialogHeader><DialogTitle>缓存视频</DialogTitle></DialogHeader><div className="max-h-[70dvh] overflow-auto"><VideoGrid videos={videos.filter((item) => item.status === "completed")} activeID={active?.id} onActivate={(item) => { setActive(item); setCacheOpen(false); }} /></div></DialogContent></Dialog>
  </section>;
}
