import { Copy, Mic2, PhoneOff, Play, Trash2 } from "lucide-react";
import { createLocalTracks, Room, RoomEvent, Track, type LocalTrack } from "livekit-client";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { publicEndpoints, publicFetch } from "@/public/api/client";
import { usePublicAuth } from "@/public/auth/public-auth";

type VoiceToken = { token: string; url: string; urls?: string[]; participant_name?: string; room_name?: string; ice_servers?: RTCIceServer[]; signal_proxy_url?: string };
type LogEntry = { id: string; time: string; text: string; level: "info" | "warn" | "error" };

const voices = [["ara","Ara · Upbeat Female"],["eve","Eve · Soothing Female"],["leo","Leo · British Male"],["rex","Rex · Calm Male"],["sal","Sal · Smooth Male"],["gork","Gork · Lazy Male"]];
const personalities = [["assistant","Assistant"],["custom","Custom"],["therapist","Therapist"],["storyteller","Storyteller"],["kids_story_time","Kids Story Time"],["kids_trivia_game","Kids Trivia Game"],["meditation","Meditation"],["doc","Grok Doc"],["unhinged","Unhinged 18+"],["sexy","Sexy 18+"],["motivation","Motivation 18+"],["conspiracy","Conspiracy"],["romantic","Romantic 18+"],["argumentative","Argumentative 18+"]];

export function VoicePage() {
  const { key } = usePublicAuth(); const [voice, setVoice] = useState("ara"); const [personality, setPersonality] = useState("assistant"); const [speed, setSpeed] = useState(1); const [status, setStatus] = useState<"idle" | "connecting" | "connected" | "error">("idle"); const [logs, setLogs] = useState<LogEntry[]>([]); const [host, setHost] = useState("-"); const roomRef = useRef<Room | null>(null); const audioRef = useRef<HTMLDivElement | null>(null); const tracksRef = useRef<LocalTrack[]>([]);
  const log = (text: string, level: LogEntry["level"] = "info") => setLogs((items) => [{ id: crypto.randomUUID(), time: new Date().toLocaleTimeString(), text, level }, ...items].slice(0, 120));
  useEffect(() => () => { void roomRef.current?.disconnect(); tracksRef.current.forEach((track) => track.stop()); }, []);
  function candidates(payload: VoiceToken) { const values: string[] = []; const add = (value?: string) => { const clean = String(value || "").trim().replace(/\/+$/, ""); if (clean && !values.includes(clean)) values.push(clean); }; const mobile = /Android|iPhone|iPad|Mobile/i.test(navigator.userAgent); if (mobile) add(payload.signal_proxy_url); (payload.urls || []).forEach(add); add(payload.url); if (!mobile) add(payload.signal_proxy_url); add("wss://livekit.grok.com"); return values.flatMap((value) => value.endsWith("/rtc") ? [value, value.slice(0, -4)] : [value, `${value}/rtc`]).filter((value, index, list) => list.indexOf(value) === index); }
  function bindRoom(room: Room) { room.on(RoomEvent.ParticipantConnected, (participant) => log(`参与者已连接: ${participant.identity}`)); room.on(RoomEvent.ParticipantDisconnected, (participant) => log(`参与者已断开: ${participant.identity}`)); room.on(RoomEvent.TrackSubscribed, (track) => { log(`订阅音轨: ${track.kind}`); if (track.kind === Track.Kind.Audio) { const element = track.attach(); element.autoplay = true; audioRef.current?.appendChild(element); } }); room.on(RoomEvent.Disconnected, () => { setStatus("idle"); log("会话已断开"); }); }
  async function connect() { if (status === "connecting" || status === "connected") return; setStatus("connecting"); log("正在获取 LiveKit Token..."); let localTracks: LocalTrack[] = []; try { if (!navigator.mediaDevices?.getUserMedia) throw new Error(window.isSecureContext ? "浏览器不支持麦克风" : "麦克风需要 HTTPS 或 localhost"); const payload = await publicFetch<VoiceToken>(key, `${publicEndpoints.voiceToken}?voice=${encodeURIComponent(voice)}&personality=${encodeURIComponent(personality)}&speed=${speed}`); if (!payload.token) throw new Error("服务端未返回有效 Token"); localTracks = await createLocalTracks({ audio: true, video: false }); tracksRef.current = localTracks; log("麦克风权限已授权"); let connected: Room | null = null; let lastError: unknown = null; let attempt = 0; for (const url of candidates(payload)) { attempt += 1; const room = new Room({ adaptiveStream: true, dynacast: true }); bindRoom(room); try { log(`连接尝试 #${attempt}: ${url}`); await room.connect(url, payload.token, { autoSubscribe: true, maxRetries: 1, websocketTimeout: 30000, peerConnectionTimeout: 20000, rtcConfig: payload.ice_servers?.length ? { iceServers: payload.ice_servers } : undefined }); connected = room; setHost(new URL(url).host); break; } catch (error) { lastError = error; log(`连接失败 #${attempt}: ${error instanceof Error ? error.message : String(error)}`, "warn"); await room.disconnect().catch(() => undefined); } } if (!connected) throw lastError || new Error("没有可用的 LiveKit 连接地址"); roomRef.current = connected; for (const track of localTracks) await connected.localParticipant.publishTrack(track); setStatus("connected"); log(`语音已开启，共尝试 ${attempt} 次`); toast.success("语音连接成功"); } catch (error) { localTracks.forEach((track) => track.stop()); tracksRef.current = []; setStatus("error"); const message = error instanceof Error ? error.message : "连接失败"; log(message, "error"); toast.error(message); } }
  async function disconnect() { tracksRef.current.forEach((track) => track.stop()); tracksRef.current = []; await roomRef.current?.disconnect(); roomRef.current = null; if (audioRef.current) audioRef.current.innerHTML = ""; setStatus("idle"); }
  async function copyLogs() { await navigator.clipboard.writeText(logs.map((item) => `[${item.time}] ${item.text}`).join("\n")); toast.success("日志已复制"); }
  return <section><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">LiveKit 陪聊</h1><p className="mt-1 text-sm text-muted-foreground">{status === "connected" ? "通话中" : status === "connecting" ? "正在连接" : status === "error" ? "连接错误" : "未连接"}</p></div>{status === "connected" ? <Button variant="destructive" onClick={() => void disconnect()}><PhoneOff className="size-4" />停止会话</Button> : <Button onClick={() => void connect()} disabled={status === "connecting"}><Play className="size-4" />{status === "connecting" ? "连接中..." : "开始会话"}</Button>}</div>
    <div className="grid gap-5 lg:grid-cols-[420px_minmax(0,1fr)]"><aside className="space-y-4 border p-4"><label className="block text-sm">声音<Select value={voice} onValueChange={setVoice}><SelectTrigger className="mt-1 h-11"><SelectValue /></SelectTrigger><SelectContent>{voices.map(([value,label]) => <SelectItem value={value} key={value}>{label}</SelectItem>)}</SelectContent></Select></label><label className="block text-sm">人格<Select value={personality} onValueChange={setPersonality}><SelectTrigger className="mt-1 h-11"><SelectValue /></SelectTrigger><SelectContent>{personalities.map(([value,label]) => <SelectItem value={value} key={value}>{label}</SelectItem>)}</SelectContent></Select></label><label className="block text-sm">语速 <span className="font-mono">{speed.toFixed(1)}x</span><input type="range" min="0.5" max="2" step="0.1" value={speed} onChange={(event) => setSpeed(Number(event.target.value))} className="mt-3 w-full" /></label><div className="grid grid-cols-2 gap-3 border-t pt-4 text-sm"><div><span className="text-xs text-muted-foreground">声音</span><p>{voice}</p></div><div><span className="text-xs text-muted-foreground">人格</span><p>{personality}</p></div><div><span className="text-xs text-muted-foreground">语速</span><p>{speed.toFixed(1)}x</p></div><div><span className="text-xs text-muted-foreground">服务器</span><p className="truncate" title={host}>{host}</p></div></div><div ref={audioRef} />
      <div className="grid h-28 grid-cols-24 items-center gap-1 overflow-hidden border bg-muted px-3" aria-label="语音状态">{Array.from({ length: 24 }, (_, index) => <span key={index} className="block w-full bg-primary transition-[height]" style={{ height: status === "connected" ? `${22 + ((index * 17) % 62)}%` : "8%" }} />)}</div></aside>
      <div><div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-semibold"><Mic2 className="size-4" />连接日志</h2><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => setLogs([])} aria-label="清空日志"><Trash2 className="size-4" /></Button><Button variant="ghost" size="icon" onClick={() => void copyLogs()} disabled={!logs.length} aria-label="复制日志"><Copy className="size-4" /></Button></div></div><div className="h-[520px] overflow-y-auto border bg-card p-3 font-mono text-xs">{logs.length ? logs.map((item) => <p key={item.id} className={item.level === "error" ? "text-destructive" : item.level === "warn" ? "text-amber-600 dark:text-amber-400" : "text-muted-foreground"}>[{item.time}] {item.text}</p>) : <p className="text-muted-foreground">开始会话后会显示连接诊断</p>}</div></div></div>
  </section>;
}
